workspace:
  base: /drone
  path: src/github.com/cp2017/go-client

pipeline:
  clone:
    image: plugins/git
    path: github.com/cp2017/go-client
  unit-test:
    image: qnib/golang
    commands:
     - ./test.sh
    environment:
     - GOPATH=/drone/
  smoke-test:
    image: qnib/golang
    commands:
      - go run main.go http --iterations 10 --delay 100 --url http://localhost:8081
      - go run main.go http --iterations 10 --delay 100 --url http://localhost:8081 --validate 200:80,500:20
      - go run main.go http --iterations 8 --delay 100 --url http://localhost:8081 --validate 200:80,500:20 --negate-validate
      - go run main.go ipfs --iterations 10 --delay 100 --swagger-path resources/services/hello-service/swagger.json
    environment:
      - GOPATH=/drone/
  build:
    image: qnib/golang
    commands:
      - mkdir -p resources/bin
      - go build -o resources/bin/go-client_linux
      - GOOS=darwin GOARCH=amd64 go build -o resources/bin/go-client_darwin
    environment:
      - GOPATH=/drone/
    when:
        event: tag
  build-musl:
    image: qnib/alpn-go-dev:1.7
    commands:
      - go build -o resources/bin/go-client_musl
    environment:
     - GOPATH=/drone/
    when:
        event: tag
  slack:
    image: plugins/slack
    channel: drone
    username: drone

services:
  ipfs:
   image: cp2017/ipfs
   pull: true
#  geth:
#   image: cp2017/geth
#   pull: true
#   container_name: geth
#   environment:
#    - GETH_TEST_DATABASE=true
  testhttpd:
   image: cp2017/testhttpd
   container_name: testhttpd
   command: "200,200,200,200,500"
   environment:
       - HTTP_PORT=8081
   pull: true
