workspace:
  base: /drone
  path: src/github.com/cp2017/go-client

pipeline:
  clone:
    image: plugins/git
    path: github.com/cp2017/go-client
  interactice:
    image: qnib/alpn-go-dev:1.7
    commands:
     - tail -f /dev/null
    environment:
     - GOPATH=/drone/
  unit-test:
    image: qnib/golang
    commands:
     - ./test.sh
    environment:
     - GOPATH=/drone/
  build:
    image: qnib/alpn-go-dev:1.7
    commands:
      - go build -o go-client_musl
    environment:
     - GOPATH=/drone/
  smoke-test:
    image: alpine:latest
    commands:
      - ./go-client_musl --help
  slack:
    image: plugins/slack
    channel: drone
    username: drone

services:
  ipfs:
   image: cp2017/ipfs
   container_name: ipfs
   pull: true
  geth:
   image: cp2017/geth
   pull: true
   container_name: geth
   environment:
    - GETH_TEST_DATABASE=true
